from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TestProject.Generated.Tests.MyFirstProject
    Test: CP005-F
    Generated by: Channyke Rodriguez (csrodriguez21@ucatolica.edu.co)
    Generated on 10/13/2021, 00:54:08
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="Dl_CRrVGkr6XQ2tp-Eg4dJ3yWlOTRQ7XPZwrxjLFM_0",
                              project_name="My first Project",
                              job_name="CP005-F")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Caso de prueba 5 fallido."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost/ActiveTime/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Scroll window by ('0','62')
    driver.execute_script("window.scrollBy(0,62)")

    # 3. Click 'user'
    user = driver.find_element(By.CSS_SELECTOR,
                               "#user")
    user.click()

    # 4. Type 'jdme1' in 'user'
    user = driver.find_element(By.CSS_SELECTOR,
                               "#user")
    user.send_keys("jdme1")

    # 5. Click 'password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#password")
    password.click()

    # 6. Type 'lindo123!' in 'password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#password")
    password.send_keys("lindo123!")

    # 7. Click 'Log in'
    log_in = driver.find_element(By.CSS_SELECTOR,
                                 "#ingresar")
    log_in.click()

    # 8. Scroll window by ('0','559')
    driver.execute_script("window.scrollBy(0,559)")

    # 9. Click 'Change Priority'
    change_priority = driver.find_element(By.CSS_SELECTOR,
                                          "#changePriority")
    change_priority.click()

    # 10. Scroll window by ('0','102')
    driver.execute_script("window.scrollBy(0,102)")

    # 11. Click 'Change'
    change = driver.find_element(By.CSS_SELECTOR,
                                 "#change-task")
    change.click()
